MariaDB [asb_portfolio]> SELECT * FROM brands;
+----+-------------+---------------------+------------------------------------------------------+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+
| id | category_id | name                | description                                          | created_at          | external_link                                                                                                                                                                                                           | type       |
+----+-------------+---------------------+------------------------------------------------------+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+
|  1 |           1 | DN SOLUTIONS        | Modern manufacturing solutions.                      | 2026-04-04 15:28:15 | https://www.dn-solutions.com/main.do                                                                                                                                                                                    | Machine    |
|  2 |           1 | MAKINO              | Extreme precision engineering.                       | 2026-04-04 15:28:15 | https://www.makino.com/                                                                                                                                                                                                 | Machine    |
|  3 |           1 | HNK                 | Specialized heavy-duty machines.                     | 2026-04-04 15:28:15 | http://en.hnkkorea.com/sub01/03_01.php                                                                                                                                                                                  | Machine    |
|  4 |           2 | KERTZ               | High-end industrial machinery.                       | 2026-04-04 15:28:15 | https://kertz-machine.com/                                                                                                                                                                                              | Tools      |
|  5 |           1 | TONE FAN            | Manufacturing drilling specialists.                  | 2026-04-04 15:28:15 | https://www.tonefan.com.tw/company.html                                                                                                                                                                                 | Machine    |
|  6 |           1 | MAZAK               | Global leader in advanced CNC machine tools.         | 2026-04-04 15:28:15 | https://www.mazak.com/id-en/                                                                                                                                                                                            | Machine    |
|  7 |           1 | BROTHER             | Compact, high-productivity CNC machining.            | 2026-04-04 15:28:15 | https://machinetool.global.brother/en-eu                                                                                                                                                                                | Machine    |
|  8 |           1 | WELE                | Large-scale, heavy-duty CNC machinery.               | 2026-04-04 15:28:15 | http://www.welegroup.com/en/                                                                                                                                                                                            | Machine    |
|  9 |           1 | SODICK              | Pioneer in precision Electrical Discharge Machining. | 2026-04-04 15:28:15 | https://sodick.com/                                                                                                                                                                                                     | Machine    |
| 10 |           1 | HYPERTHERM          | World leader in industrial cutting solutions.        | 2026-04-04 15:28:15 | https://www.hypertherm.com/                                                                                                                                                                                             | Machine    |
| 11 |           2 | TOPTUL              | Chrome Vanadium professional tools.                  | 2026-04-04 15:28:15 | https://www.toptul.com/en/product.html                                                                                                                                                                                  | Tools      |
| 12 |           2 | ELORA               | High-end German manufacturing quality.               | 2026-04-04 15:28:15 | https://products.elora.de/en/Products/Pliers/Precision-Pliers/Module-Pliers-OMS-5.html                                                                                                                                  | Tools      |
| 13 |           2 | TEKIRO              | Leading industrial tool brand.                       | 2026-04-04 15:28:15 | https://tekiro.com/                                                                                                                                                                                                     | Tools      |
| 14 |           2 | MAKITA              | Global leader in power tools.                        | 2026-04-04 15:28:15 | https://indomakita.com/                                                                                                                                                                                                 | Tools      |
| 15 |           2 | BOSCH REXROTH       | Reliable German engineering.                         | 2026-04-04 15:28:15 | https://www.boschrexroth.com/en/us/products/industrial-solutions/tightening-technology/bosch-production-tools/                                                                                                          | Tools      |
| 16 |           2 | HYTORC              | The world primary bolting solution.                  | 2026-04-04 15:28:16 | https://www.hytorc.com/id/stealth                                                                                                                                                                                       | Tools      |
| 17 |           3 | Caterpillar         | Construction and mining giants.                      | 2026-04-04 15:28:16 | https://www.caterpillar.com/                                                                                                                                                                                            | Machine    |
| 18 |           3 | Komatsu             | High-performance heavy equipment.                    | 2026-04-04 15:28:16 | https://www.komatsu.co.id/spare-parts                                                                                                                                                                                   | Machine    |
| 19 |           3 | CUMMINS             | Advanced power solutions.                            | 2026-04-04 15:28:16 | https://www.cummins.com/                                                                                                                                                                                                | Machine    |
| 20 |           3 | LINCOLN             | Industrial maintenance experts.                      | 2026-04-04 15:28:16 | https://www.skf.com/us/products/lubrication-management/lincolnindustrial                                                                                                                                                | Tools      |
| 21 |           4 | Siemens             | NULL                                                 | 2026-04-06 11:00:39 | https://www.siemens.com/en-us/                                                                                                                                                                                          | Electrical |
| 22 |           4 | Schneider Electric  | NULL                                                 | 2026-04-06 11:00:39 | https://www.se.com/id/id/all-products/                                                                                                                                                                                  | Electrical |
| 23 |           4 | Yaskawa             | NULL                                                 | 2026-04-06 11:00:39 | https://www.yaskawa.co.id/                                                                                                                                                                                              | Electrical |
| 24 |           4 | ABB                 | NULL                                                 | 2026-04-06 11:00:39 | https://www.abb.com/global/en                                                                                                                                                                                           | Electrical |
| 25 |           4 | Omron               | NULL                                                 | 2026-04-06 11:00:39 | https://www.omron.co.id/                                                                                                                                                                                                | Electrical |
| 26 |           4 | Hager               | NULL                                                 | 2026-04-06 11:00:39 | https://hager.com/id                                                                                                                                                                                                    | Electrical |
| 27 |           4 | CHINT               | NULL                                                 | 2026-04-06 11:00:39 | https://www.chintglobal.com/global/en/home.html                                                                                                                                                                         | Electrical |
| 28 |           4 | Eaton               | NULL                                                 | 2026-04-06 11:00:39 | https://www.eaton.com/us/en-us.html                                                                                                                                                                                     | Electrical |
| 29 |           4 | General Electric    | NULL                                                 | 2026-04-06 11:00:39 | https://www.ge.com/                                                                                                                                                                                                     | Electrical |
| 30 |           4 | Fuji Electric       | NULL                                                 | 2026-04-06 11:00:39 | https://www.fujielectric.com/products/mc/                                                                                                                                                                               | Electrical |
| 31 |           4 | Mitsubishi Electric | NULL                                                 | 2026-04-06 11:00:39 | https://www.mitsubishielectric.com/fa/id_id/products/index.html                                                                                                                                                         | Electrical |
| 32 |           4 | LS Electric         | NULL                                                 | 2026-04-06 11:00:39 | https://www.ls-electric.com/                                                                                                                                                                                            | Electrical |
| 33 |           4 | Autonics            | NULL                                                 | 2026-04-06 11:00:39 | https://www.autonics.com/id/main                                                                                                                                                                                        | Electrical |
| 34 |           4 | Legrand             | NULL                                                 | 2026-04-06 11:00:39 | https://www.legrand.co.id/en                                                                                                                                                                                            | Electrical |
| 35 |           4 | SMC                 | NULL                                                 | 2026-04-06 11:00:39 | https://www.smcworld.com/en-jp/                                                                                                                                                                                         | Electrical |
| 36 |           4 | Fort                | NULL                                                 | 2026-04-06 11:00:39 | https://fortindo.id/?gad_source=1&gad_campaignid=20974034375&gbraid=0AAAAAqxjpUWRiTY2H_e7REYzgUNQRO52S&gclid=Cj0KCQjwkMjOBhC5ARIsADIdb3cN9ruL5wOInvhDN4DFiYiR2UICRuwZXjgiyB_P3lvN0vlS9RaMSE8aAt_tEALw_wcB               | Electrical |
| 37 |           4 | Megger              | NULL                                                 | 2026-04-06 11:00:39 | https://www.megger.com/en                                                                                                                                                                                               | Electrical |
| 38 |           4 | JEMBO CABLE         | NULL                                                 | 2026-04-06 11:00:39 | https://jembo.co.id/id                                                                                                                                                                                                  | Electrical |
| 39 |           4 | Supreme             | NULL                                                 | 2026-04-06 11:00:39 | https://www.sucaco.com/                                                                                                                                                                                                 | Electrical |
| 40 |           4 | Kabelindo           | NULL                                                 | 2026-04-06 11:00:39 | https://www.kabelindo.co.id/                                                                                                                                                                                            | Electrical |
| 41 |           4 | KABELMETAL          | NULL                                                 | 2026-04-06 11:00:39 | https://kabelmetalindonesia.co.id/?gad_source=1&gad_campaignid=22519525571&gbraid=0AAAAA9tcGsukpLHTzIzxIPH83lBSxfBUN&gclid=Cj0KCQjwkMjOBhC5ARIsADIdb3dgGKMqYGihGrrTec1dxAmO03m45j_xAhfZCFlcufp1EahUKNfnXrgaAs4sEALw_wcB | Electrical |
| 42 |           4 | VOKSEL ELECTRIC     | NULL                                                 | 2026-04-06 11:00:39 | https://www.voksel.co.id/id                                                                                                                                                                                             | Electrical |
| 43 |           4 | Teco                | NULL                                                 | 2026-04-06 11:00:39 | https://teco.id/contact/                                                                                                                                                                                                | Electrical |
| 44 |           4 | Toshiba             | NULL                                                 | 2026-04-06 11:00:39 | https://www.toshiba-tips.co.jp/en/products/motor/                                                                                                                                                                       | Electrical |
| 45 |           4 | Kiepe               | NULL                                                 | 2026-04-06 11:00:39 | https://kiepe-group.com/en/                                                                                                                                                                                             | Electrical |
| 46 |           4 | Raychem             | NULL                                                 | 2026-04-06 11:00:39 | https://www.raychem.com/en/home.html                                                                                                                                                                                    | Electrical |
| 47 |           2 | Sandvik Coromant    | NULL                                                 | 2026-04-06 11:00:39 | https://www.sandvik.coromant.com/en-gb                                                                                                                                                                                  | Tools      |
| 48 |           2 | Kennametal          | NULL                                                 | 2026-04-06 11:00:39 | https://www.kennametal.com/us/en/home.html                                                                                                                                                                              | Tools      |
| 49 |           2 | Dormer Pramet       | NULL                                                 | 2026-04-06 11:00:39 | https://www.dormerpramet.com/                                                                                                                                                                                           | Tools      |
| 50 |           2 | Hartner             | NULL                                                 | 2026-04-06 11:00:39 | https://www.hartner.de/?page_id=96&lang=en                                                                                                                                                                              | Tools      |
| 51 |           2 | ROHM                | NULL                                                 | 2026-04-06 11:00:39 | https://www.roehm.biz/en/                                                                                                                                                                                               | Tools      |
| 52 |           2 | Nachi               | NULL                                                 | 2026-04-06 11:00:39 | https://www.nachi.de/product-portfolio/tools.html                                                                                                                                                                       | Tools      |
| 53 |           4 | Allen-Bradley       | NULL                                                 | 2026-04-06 11:33:08 | https://www.rockwellautomation.com/en-us/products/hardware/allen-bradley.html                                                                                                                                           | Electrical |
| 54 |           4 | IFM                 | NULL                                                 | 2026-04-06 11:33:08 | https://www.ifm.com/id/in                                                                                                                                                                                               | Electrical |
| 55 |           4 | Weintek             | NULL                                                 | 2026-04-06 11:33:08 | https://www.weintek.com/                                                                                                                                                                                                | Electrical |
| 56 |           4 | Fluke               | NULL                                                 | 2026-04-06 11:33:08 | https://www.fluke.com/                                                                                                                                                                                                  | Electrical |
| 57 |           4 | Ametek              | NULL                                                 | 2026-04-06 11:33:08 | https://www.ametekcalibration.com/                                                                                                                                                                                      | Electrical |
| 58 |           4 | Olympus             | NULL                                                 | 2026-04-06 11:33:08 | https://www.olympus-global.com/                                                                                                                                                                                         | Electrical |
| 59 |           4 | HIOKI               | NULL                                                 | 2026-04-06 11:33:08 | https://hioki.co.id/                                                                                                                                                                                                    | Electrical |
| 60 |           4 | Kyoritsu            | NULL                                                 | 2026-04-06 11:33:08 | https://www.kew-ltd.co.jp/en/                                                                                                                                                                                           | Electrical |
| 61 |           4 | Yokogawa            | NULL                                                 | 2026-04-06 11:33:08 | https://www.yokogawa.com/id/solutions/products-and-services/                                                                                                                                                            | Electrical |
| 62 |           4 | Flir                | NULL                                                 | 2026-04-06 11:33:08 | https://www.flir.com/                                                                                                                                                                                                   | Electrical |
| 63 |           4 | Rosemount           | NULL                                                 | 2026-04-06 11:33:08 | http://emerson.cn/en-cn                                                                                                                                                                                                 | Electrical |
| 64 |           3 | Volvo               | NULL                                                 | 2026-04-06 11:33:08 | https://www.volvotrucks.id/id-id/services/parts-accessories/parts.html                                                                                                                                                  | Machine    |
| 65 |           3 | Belaz               | NULL                                                 | 2026-04-06 11:33:08 | https://belaz.by/en/                                                                                                                                                                                                    | Machine    |
| 66 |           3 | Kamaz               | NULL                                                 | 2026-04-06 11:33:08 | https://kamazexport.ae/                                                                                                                                                                                                 | Machine    |
| 67 |           5 | Grundfos            | NULL                                                 | 2026-04-06 11:33:08 | https://www.grundfos.com/                                                                                                                                                                                               | Mechanical |
| 68 |           5 | TORISHIMA           | NULL                                                 | 2026-04-06 11:33:08 | https://www.torishima.co.jp/en/product/                                                                                                                                                                                 | Mechanical |
| 69 |           5 | Atlas Copco         | NULL                                                 | 2026-04-06 11:33:08 | https://www.atlascopco.com/id-id                                                                                                                                                                                        | Mechanical |
| 70 |           5 | Ingersoll Rand      | NULL                                                 | 2026-04-06 11:33:08 | https://www.ingersollrand.com/en-apac/products/                                                                                                                                                                         | Mechanical |
| 71 |           5 | FAG                 | NULL                                                 | 2026-04-06 11:33:08 | https://www.schaeffler.co.id/en/news_media/media_library/videos/downloadcenter_global_videos/?videoid=87565058&pvideoid=87567488&tab=mediathek-vid&subfilter=app:dc                                                     | Mechanical |
| 72 |           5 | SKF                 | NULL                                                 | 2026-04-06 11:33:08 | https://www.skf.com/id                                                                                                                                                                                                  | Mechanical |
| 73 |           5 | Fersa               | NULL                                                 | 2026-04-06 11:33:08 | https://www.fersa.com/en/                                                                                                                                                                                               | Mechanical |
| 74 |           5 | Bakrie Pipe         | NULL                                                 | 2026-04-06 11:33:08 | https://bakrie-pipe.com/public/id/berita-terkini/detail/piping-vs-pipeline-memahami-perbedaan-dan-standar-di-industri-migas                                                                                             | Mechanical |
| 75 |           5 | Bando               | NULL                                                 | 2026-04-06 11:33:08 | https://www.bandoindonesia.com/product-cov.html                                                                                                                                                                         | Mechanical |
| 76 |           5 | Gates               | NULL                                                 | 2026-04-06 11:33:08 | https://www.gates.com/us/en.html                                                                                                                                                                                        | Mechanical |
+----+-------------+---------------------+------------------------------------------------------+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+
76 rows in set (0.123 sec)

MariaDB [asb_portfolio]> SELECT * FROM categories;
+----+-------------------------+------------------------------------------------------------------------------+---------------------+
| id | name                    | description                                                                  | created_at          |
+----+-------------------------+------------------------------------------------------------------------------+---------------------+
|  1 | Machine Products        | Advanced CNC and manufacturing machinery for precision production.           | 2026-04-04 15:28:15 |
|  2 | Tools Products          | Precision engineering and heavy-duty durability for industrial applications. | 2026-04-04 15:28:15 |
|  3 | Product Support         | Heavy machinery and core equipment for large-scale operations.               | 2026-04-04 15:28:15 |
|  4 | Electrical & Automation | Comprehensive electrical and automation products                             | 2026-04-06 11:00:39 |
|  5 | Mechanical Products     |                                                                              | 2026-04-06 11:33:08 |
+----+-------------------------+------------------------------------------------------------------------------+---------------------+
5 rows in set (0.001 sec)

MariaDB [asb_portfolio]> SELECT * FROM photos;
+----+----------+-------------+-------------------------+------------------------------------------------------+-----+------------+------+---------------------+
| id | brand_id | category_id | filename                | filepath                                             | url | mimetype   | size | uploaded_at         |
+----+----------+-------------+-------------------------+------------------------------------------------------+-----+------------+------+---------------------+
|  1 |       24 |        NULL | ABB.png                 | assets/ELECTRICAL-AUTOMATION/ABB.png                 |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
|  2 |       53 |        NULL | ALLEN-BRADLEY.png       | assets/ELECTRICAL-AUTOMATION/ALLEN-BRADLEY.png       |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
|  3 |       57 |        NULL | AMETEK.png              | assets/ELECTRICAL-AUTOMATION/AMETEK.png              |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
|  4 |       33 |        NULL | AUTONICS.png            | assets/ELECTRICAL-AUTOMATION/AUTONICS.png            |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
|  5 |       27 |        NULL | CHINT.png               | assets/ELECTRICAL-AUTOMATION/CHINT.png               |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
|  6 |       28 |        NULL | EATON.png               | assets/ELECTRICAL-AUTOMATION/EATON.png               |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
|  7 |       62 |        NULL | FLIR.png                | assets/ELECTRICAL-AUTOMATION/FLIR.png                |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
|  8 |       56 |        NULL | FLUKE.png               | assets/ELECTRICAL-AUTOMATION/FLUKE.png               |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
|  9 |       36 |        NULL | FORT.png                | assets/ELECTRICAL-AUTOMATION/FORT.png                |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 10 |       30 |        NULL | FUJI ELECTRIC.png       | assets/ELECTRICAL-AUTOMATION/FUJI ELECTRIC.png       |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 11 |       29 |        NULL | GENERAL ELECTRIC.png    | assets/ELECTRICAL-AUTOMATION/GENERAL ELECTRIC.png    |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 12 |       26 |        NULL | HAGER.png               | assets/ELECTRICAL-AUTOMATION/HAGER.png               |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 13 |       59 |        NULL | HIOKI.png               | assets/ELECTRICAL-AUTOMATION/HIOKI.png               |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 14 |       54 |        NULL | IFM.png                 | assets/ELECTRICAL-AUTOMATION/IFM.png                 |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 15 |       38 |        NULL | JEMBO CABLE.png         | assets/ELECTRICAL-AUTOMATION/JEMBO CABLE.png         |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 16 |       40 |        NULL | KABELINDO.png           | assets/ELECTRICAL-AUTOMATION/KABELINDO.png           |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 17 |       41 |        NULL | KABELMETAL.jpeg         | assets/ELECTRICAL-AUTOMATION/KABELMETAL.jpeg         |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 18 |       45 |        NULL | KIEPE.png               | assets/ELECTRICAL-AUTOMATION/KIEPE.png               |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 19 |       60 |        NULL | KYORITSU.png            | assets/ELECTRICAL-AUTOMATION/KYORITSU.png            |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 20 |       34 |        NULL | LEGRAND.png             | assets/ELECTRICAL-AUTOMATION/LEGRAND.png             |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 21 |       32 |        NULL | LS ELECTRIC.png         | assets/ELECTRICAL-AUTOMATION/LS ELECTRIC.png         |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 22 |       37 |        NULL | MEGGER.png              | assets/ELECTRICAL-AUTOMATION/MEGGER.png              |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 23 |       31 |        NULL | MITSUBISHI ELECTRIC.png | assets/ELECTRICAL-AUTOMATION/MITSUBISHI ELECTRIC.png |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 24 |       58 |        NULL | OLYMPUS.png             | assets/ELECTRICAL-AUTOMATION/OLYMPUS.png             |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 25 |       25 |        NULL | OMRON.png               | assets/ELECTRICAL-AUTOMATION/OMRON.png               |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 26 |       46 |        NULL | RAYCHEM.png             | assets/ELECTRICAL-AUTOMATION/RAYCHEM.png             |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 27 |       63 |        NULL | ROSEMOUNT.png           | assets/ELECTRICAL-AUTOMATION/ROSEMOUNT.png           |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 28 |       22 |        NULL | SCHNEIDER ELECTRIC.png  | assets/ELECTRICAL-AUTOMATION/SCHNEIDER ELECTRIC.png  |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 29 |       21 |        NULL | SIEMENS.png             | assets/ELECTRICAL-AUTOMATION/SIEMENS.png             |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 30 |       35 |        NULL | SMC.png                 | assets/ELECTRICAL-AUTOMATION/SMC.png                 |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 31 |       39 |        NULL | SUPREME.png             | assets/ELECTRICAL-AUTOMATION/SUPREME.png             |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 32 |       43 |        NULL | TECO.png                | assets/ELECTRICAL-AUTOMATION/TECO.png                |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 33 |       44 |        NULL | TOSHIBA.png             | assets/ELECTRICAL-AUTOMATION/TOSHIBA.png             |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 34 |       42 |        NULL | VOKSEL ELECTRIC.png     | assets/ELECTRICAL-AUTOMATION/VOKSEL ELECTRIC.png     |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 35 |       55 |        NULL | WEINTEK.png             | assets/ELECTRICAL-AUTOMATION/WEINTEK.png             |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 36 |       23 |        NULL | YASKAWA.png             | assets/ELECTRICAL-AUTOMATION/YASKAWA.png             |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 37 |       61 |        NULL | YOKOGAWA.png            | assets/ELECTRICAL-AUTOMATION/YOKOGAWA.png            |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 38 |       69 |        NULL | ATLAS COPCO.png         | assets/machine-products/ATLAS COPCO.png              |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 39 |       74 |        NULL | BAKRIE PIPE.png         | assets/machine-products/BAKRIE PIPE.png              |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 40 |       75 |        NULL | BANDO.png               | assets/machine-products/BANDO.png                    |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 41 |        7 |        NULL | BROTHER.png             | assets/machine-products/BROTHER.png                  |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 42 |       19 |        NULL | CUMMINS.png             | assets/machine-products/CUMMINS.png                  |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 43 |        1 |        NULL | DN SOLUTIONS.png        | assets/machine-products/DN SOLUTIONS.png             |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 44 |       71 |        NULL | FAG.png                 | assets/machine-products/FAG.png                      |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 45 |       73 |        NULL | FERSA.png               | assets/machine-products/FERSA.png                    |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 46 |       76 |        NULL | GATES.png               | assets/machine-products/GATES.png                    |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 47 |       67 |        NULL | GRUNDFOS.png            | assets/machine-products/GRUNDFOS.png                 |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 48 |        3 |        NULL | HNK.png                 | assets/machine-products/HNK.png                      |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 49 |       10 |        NULL | HYPERTHERM.png          | assets/machine-products/HYPERTHERM.png               |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 50 |       70 |        NULL | INGERSOLL RAND.png      | assets/machine-products/INGERSOLL RAND.png           |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 51 |        2 |        NULL | MAKINO.png              | assets/machine-products/MAKINO.png                   |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 52 |        6 |        NULL | MAZAK.png               | assets/machine-products/MAZAK.png                    |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 53 |       72 |        NULL | SKF.png                 | assets/machine-products/SKF.png                      |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 54 |        9 |        NULL | SODICK.png              | assets/machine-products/SODICK.png                   |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 55 |        5 |        NULL | TONE FAN.png            | assets/machine-products/TONE FAN.png                 |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 56 |       68 |        NULL | TORISHIMA.png           | assets/machine-products/TORISHIMA.png                |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 57 |        8 |        NULL | WELE.png                | assets/machine-products/WELE.png                     |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 58 |       65 |        NULL | BELAZ.png               | assets/product-support/BELAZ.png                     |     | image/jpeg |    0 | 2026-04-06 13:32:43 |
| 59 |       17 |        NULL | CATERPILLAR.png         | assets/product-support/CATERPILLAR.png               |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 60 |       66 |        NULL | KAMAZ.png               | assets/product-support/KAMAZ.png                     |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 61 |       18 |        NULL | KOMATSU.png             | assets/product-support/KOMATSU.png                   |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 62 |       20 |        NULL | LINCOLN.png             | assets/product-support/LINCOLN.png                   |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 63 |       64 |        NULL | VOLVO.png               | assets/product-support/VOLVO.png                     |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 64 |       15 |        NULL | BOSCH REXROTH.png       | assets/tools-products/BOSCH REXROTH.png              |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 65 |       49 |        NULL | DORMER PRAMET.webp      | assets/tools-products/DORMER PRAMET.webp             |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 66 |       12 |        NULL | ELORA.png               | assets/tools-products/ELORA.png                      |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 67 |       50 |        NULL | HARTNER.png             | assets/tools-products/HARTNER.png                    |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 68 |       16 |        NULL | HYTORC.png              | assets/tools-products/HYTORC.png                     |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 69 |       48 |        NULL | KENNAMETAL.png          | assets/tools-products/KENNAMETAL.png                 |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 70 |        4 |        NULL | KERTZ.png               | assets/tools-products/KERTZ.png                      |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 71 |       14 |        NULL | MAKITA.png              | assets/tools-products/MAKITA.png                     |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 72 |       52 |        NULL | NACHI.png               | assets/tools-products/NACHI.png                      |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 73 |       51 |        NULL | ROHM.png                | assets/tools-products/ROHM.png                       |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 74 |       47 |        NULL | SANDVIK COROMANT.png    | assets/tools-products/SANDVIK COROMANT.png           |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 75 |       13 |        NULL | TEKIRO.png              | assets/tools-products/TEKIRO.png                     |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
| 76 |       11 |        NULL | TOPTUL.png              | assets/tools-products/TOPTUL.png                     |     | image/jpeg |    0 | 2026-04-06 13:32:44 |
+----+----------+-------------+-------------------------+------------------------------------------------------+-----+------------+------+---------------------+
76 rows in set (0.002 sec)

MariaDB [asb_portfolio]> SELECT * FROM products;
+----+----------+--------------------------------+---------------------+
| id | brand_id | name                           | created_at          |
+----+----------+--------------------------------+---------------------+
|  1 |        1 | CNC Milling                    | 2026-04-04 15:28:16 |
|  2 |        1 | Lathe Machines                 | 2026-04-04 15:28:16 |
|  3 |        2 | Horizontal Milling             | 2026-04-04 15:28:16 |
|  4 |        2 | EDM Machines                   | 2026-04-04 15:28:16 |
|  5 |        3 | Vertical Lathes                | 2026-04-04 15:28:16 |
|  6 |        3 | Boring Machines                | 2026-04-04 15:28:16 |
|  7 |        4 | Precision Cutting              | 2026-04-04 15:28:16 |
|  8 |        4 | Milling                        | 2026-04-04 15:28:16 |
|  9 |        5 | Radial Drilling                | 2026-04-04 15:28:16 |
| 10 |        5 | Industrial Drills              | 2026-04-04 15:28:16 |
| 11 |        6 | Multi-tasking CNC              | 2026-04-04 15:28:16 |
| 12 |        6 | 5-Axis Machining               | 2026-04-04 15:28:16 |
| 13 |        6 | Turning Centers                | 2026-04-04 15:28:16 |
| 14 |        7 | SPEEDIO Tapping Centers        | 2026-04-04 15:28:16 |
| 15 |        7 | High-Speed CNC                 | 2026-04-04 15:28:16 |
| 16 |        8 | Bridge/Double-Column Machining | 2026-04-04 15:28:16 |
| 17 |        8 | Boring Machines                | 2026-04-04 15:28:16 |
| 18 |        9 | Wire & Sinker EDM              | 2026-04-04 15:28:16 |
| 19 |        9 | High-Speed Milling             | 2026-04-04 15:28:16 |
| 20 |        9 | Metal 3D Printing              | 2026-04-04 15:28:16 |
| 21 |       10 | Plasma Cutting Systems         | 2026-04-04 15:28:16 |
| 22 |       10 | CNC Motion Control             | 2026-04-04 15:28:16 |
| 23 |       11 | Wrench Set                     | 2026-04-04 15:28:16 |
| 24 |       11 | Socket Set                     | 2026-04-04 15:28:16 |
| 25 |       11 | Torque Tools                   | 2026-04-04 15:28:16 |
| 26 |       12 | Spanners                       | 2026-04-04 15:28:16 |
| 27 |       12 | Pliers                         | 2026-04-04 15:28:16 |
| 28 |       12 | Workshops                      | 2026-04-04 15:28:16 |
| 29 |       13 | Hand Tools                     | 2026-04-04 15:28:16 |
| 30 |       13 | Automotive Tools               | 2026-04-04 15:28:16 |
| 31 |       14 | Cordless Drill                 | 2026-04-04 15:28:16 |
| 32 |       14 | Grinder                        | 2026-04-04 15:28:16 |
| 33 |       14 | Circular Saw                   | 2026-04-04 15:28:16 |
| 34 |       15 | Power Tools                    | 2026-04-04 15:28:16 |
| 35 |       15 | Measuring Tools                | 2026-04-04 15:28:16 |
| 36 |       16 | Hydraulic Torque Wrench        | 2026-04-04 15:28:16 |
| 37 |       16 | Bolt Tensioners                | 2026-04-04 15:28:16 |
| 38 |       17 | Excavators                     | 2026-04-04 15:28:16 |
| 39 |       17 | Dump Trucks                    | 2026-04-04 15:28:16 |
| 40 |       17 | Bulldozers                     | 2026-04-04 15:28:16 |
| 41 |       18 | Excavators                     | 2026-04-04 15:28:16 |
| 42 |       18 | Wheel Loaders                  | 2026-04-04 15:28:16 |
| 43 |       19 | Diesel Engines                 | 2026-04-04 15:28:16 |
| 44 |       19 | Power Generators               | 2026-04-04 15:28:16 |
| 45 |       20 | Auto Lubrication               | 2026-04-04 15:28:16 |
| 46 |       20 | Welding Gear                   | 2026-04-04 15:28:16 |
+----+----------+--------------------------------+---------------------+
46 rows in set (0.003 sec)